spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradewallet
    username: trade
    password: trade
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
